#!/usr/bin/python3

import argparse
import os
import subprocess

IMAGE_NAME = "cacophony-api"
CONTAINER_NAME = "cacophony-api"

parser = argparse.ArgumentParser(
    description="Run cacophony API server inside a Docker container"
)
parser.add_argument(
    "--isolate",
    default=False,
    action="store_true",
    help="Re-install npm dependencies, don't restart server when code changes",
)
parser.add_argument(
    "--background",
    default=False,
    action="store_true",
    help="Run container in background & don't show container logs",
)
# Set to false if your current user is already in the docker user group
parser.add_argument(
    "--no-sudo",
    default=False,
    action="store_true",
    help="Run commands without sudo",
)
args = parser.parse_args()
if not os.path.exists("node_modules"):
    print("Node modules have not been installed yet, doing so now")
    subprocess.call(["npm", "install"])

print("Stopping {} container (if running)".format(CONTAINER_NAME))
remove_container_cmd = ["sudo", "docker", "rm", "--force", CONTAINER_NAME]
if args.no_sudo:
    remove_container_cmd.remove("sudo")

subprocess.call(
    remove_container_cmd,
    stdout=subprocess.DEVNULL,
    stderr=subprocess.STDOUT,
)

print("Building container")
build_container_cmd = ["sudo", "docker", "build", ".", "-t", IMAGE_NAME]
if args.no_sudo:
    build_container_cmd.remove("sudo")
subprocess.check_call(build_container_cmd)

print("Starting container")
run_cmd = [
    "sudo",
    "docker",
    "run",
    "-td",
    "--rm",
    "--name",
    CONTAINER_NAME,
    "-p",
    "1080:1080",
    "-p",
    "2008:2008",
    "-p",
    "9001:9001",
    "-p",
    "5400:5432",
    "--volume",
    os.getcwd() + ":/app",
]

if args.no_sudo:
    run_cmd.remove("sudo")

if args.isolate:
    run_cmd.extend(
        [
            "-e",
            "ISOLATE=1",  # copy code to a separate location & run "npm install"
            "--volume",
            "/app/node_modules",  # don't pass node_modules directory through
            "-e",
            "NODE_BIN=node",  # use node to run the server
        ]
    )
else:
    run_cmd.extend(
        [
            "-e",
            "NODE_BIN=nodemon",  # use nodemon to restart the server when the code changes
        ]
    )
run_cmd.append(IMAGE_NAME)
subprocess.check_call(run_cmd)

if not args.background:
    print("\nShowing container logs")
    try:
        docker_logs_cmd = ["sudo", "docker", "logs", "--follow", CONTAINER_NAME]
        if args.no_sudo:
            docker_logs_cmd.remove("sudo")
        subprocess.call(docker_logs_cmd)
    except (KeyboardInterrupt, PermissionError):
        pass
